### ISSUE TITLE
"Dark mode" color option

### ISSUE THREAD

**Issue by cl8n** [cl8n/project-loved-web#10]
the website should have a "light" and "dark" color palette. some way to set preference per-browser as well, falling back to OS preference, then falling back to \<pick one\>

**Comment by cl8n** [comment]
added support for this but not the actual colors. need help finding good ones ;_ ;

**Comment by huuishuu** [comment]
> 
> 
> added support for this but not the actual colors. need help finding good ones ;_ ;

How about the ones @abraker95 used in this issue? https://github.com/cl8n/project-loved-web/issues/39

#181a1b for the background
#e25895 for the text

![](https://user-images.githubusercontent.com/4358724/129661743-56bf67a8-03c2-41d2-8989-b5de65390cc5.png)

**Comment by cl8n** [comment]
there be lotsa colors https://github.com/cl8n/project-loved-web/blob/71f156f9d5cf3f5a134028213dd46e2cc7e11597/client/src/styles/_colors.scss#L38-L59

**Comment by abraker95** [comment]
Btw I am using dark reader extension to get the dark mode colors. here is a screenshot of the full site

![](https://i.imgur.com/nbhMqwy.png)
