### ISSUE TITLE
No ability to set Alumni for metadata, moderators, developers or news editors

### ISSUE THREAD

**Issue by huuishuu** [cl8n/project-loved-web#110]
Think that's pretty important, no? Especially if we get people from the metadata team, for example, that retire from their duties.

Currently we can only set non-captain users as "alumni" and they'll be grouped into "Other", which is fine for people like verto & Striiker who've made a few videos for Project Loved, but people like eiri- used to be a Beatmap Metadata reviewer for a long time & doesn't feel right to group them together with the rest.

If you don't see this as something that's super important, feel free to close with no change.

**Comment by cl8n** [comment]
it was set up as a separate role because that's just how I did it, the other stuff wasn't intentionally excluded. alumni should probably act as a modifier to the other role settings

also I think eiri- was never added to this stuff cuz they didn't do anything, double-check that though I don't remember too well

**Comment by cl8n** [comment]
not very related but I've also had written down on some other list for a while that I should double-check if ThatsNotAName (<https://osu.ppy.sh/users/9682904>) made videos for loved and add to alumni if so

**Comment by cl8n** [comment]
read back thru old chat logs and fixed the 2 ppl mentioned above. @huuishuu where did u find anything about eiri- in the first place?

**Comment by huuishuu** [comment]
> 
> 
> read back thru old chat logs and fixed the 2 ppl mentioned above. @huuishuu where did u find anything about eiri- in the first place?

Basing it off of an outdated translation for the [Project Loved Team wiki page](https://osu.ppy.sh/wiki/pl/People/The_Team/Project_Loved_Team). The one I linked is the Polish one and eiri- is directly mentioned.

**Comment by cl8n** [comment]
can be safely ignored :see_no_evil:
