### ISSUE TITLE
Secondary sorting does not work

### ISSUE THREAD

**Issue by huuishuu** [cl8n/project-loved-web#111]
![](https://i.imgur.com/y7Y9Nfh.png)

^ The primary sorting method works just fine. However, if you set that & then try to use the second one, it does not change anything. Here's an example:

![](https://i.imgur.com/yUVnUtP.png)

![](https://i.imgur.com/EtJDeNv.png)

Changed to Favs + Plays but it made absolutely no difference in the sorting on any page.

Sorting by ascending/descending does work though.

**Comment by cl8n** [comment]
well you chose a primary sort that has all different values. not sure what you were expecting

**Comment by huuishuu** [comment]
> 
> 
> well you chose a primary sort that has different value for each map. not sure what you were expecting

I was kind of expecting it to work the way it did on the Google sheets.

![](https://i.imgur.com/yhMVBen.png)

(sorting, for example, by favs & plays instead of priority & score)

**Comment by cl8n** [comment]
what is google sheet screenshot supposed to show idgi

**Comment by cl8n** [comment]
https://discord.com/channels/188630481301012481/384640068847009792/908287943481917480
