### ISSUE TITLE
Add ability to search through submissions

### ISSUE THREAD

**Issue by huuishuu** [cl8n/project-loved-web#115]
Something I frequently used on Google sheets was to ctrl + f for a map to see if it's submitted. Something similar should be present on this website as well, would be a really good QoL feature, especially as the number of submissions continues to grow. In osu!mania it's already a pain to go through, considering they have a whopping 37 pages of submissions.

I've asked around the captains & the general communities in the osu!taiko & osu!mania community servers, as well as the captain+metadata teams and this has unanimous agreement

**Comment by cl8n** [comment]
the show of hands is kinda pointless cuz like... why would you say anything but "yes"
and none of these screenshots have further info abt wanted feature or use cases etc

**Comment by huuishuu** [comment]
The most common use-case I can gather in favor of this feature is primarily to check whether a certain map has been submitted already. Currently it's super tedious to do so, requiring either to either:
- (re)submit the map yourself
- go through each page individually and ctrl+f the map name to see if its there

First option is generally fine but I'm pretty sure we'd rather not spam map submissions to see if said map has been submitted already. (using myself as an example - I don't want to be the one to submit my own maps to check if anyone submitted one of my maps for Loved)

Second option is incredibly tedious and needlessly time-consuming, especially on osu!standard and osu!mania when there's already like 20+ pages on each game mode with submissions. osu!taiko and osu!catch captains don't see this as a massive priority though, given the low amount of submissions & activity from said captains on those pages.
