### ISSUE TITLE
Menu text is hard to read in dark mode

### ISSUE THREAD

**Issue by Hiviexd** [cl8n/project-loved-web#117]
![image](https://user-images.githubusercontent.com/62819481/144750544-54e59daf-bb3d-455b-bad6-f74bc4625c7f.png)

**Comment by cl8n** [comment]
what browser is this, and do you have system or browser settings for global light/dark theme?

**Comment by cl8n** [comment]
i got a similar result on chromium so i assume that's what you're using. should work now

**Comment by Hiviexd** [comment]
i'm using chrome, and it's fixed now thx
