### ISSUE TITLE
Manually move a "current round" into "past round"

### ISSUE THREAD

**Issue by Pachiru** [cl8n/project-loved-web#127]
I think it could be a good feature (not particularly important though) since it happened that some rounds stayed for a bit longer even after the round was over, i.e. January 2022 - I know it should be move into past round when all maps are moved into Loved (or not) but I think having a control over it could be better imo

**Comment by cl8n** [comment]
it's intentional that they stay "current" until everything is resolved, looks like January has one map that still isn't loved even tho it passed voting--- asked about it on discord

**Comment by cl8n** [comment]
closing cuz it does seem like a one-off issue that intentionally has this display on site
