### ISSUE TITLE
Update restricted user style

### ISSUE THREAD

**Issue by cl8n** [cl8n/project-loved-web#196]
it should probably just say "(restricted)" or something to be clear

also mentioned in discord, reviews created by restricted users should be dimmed in some way

**Comment by huuishuu** [comment]
Restricted users should not be able to use the site, period, I think.

Remember, the point of a restriction is that you cannot interact with the osu! community. Project Loved directly uses osu! accounts to authenticate, so why should rulebreakers on the actual osu! site be allowed to roam freely on loved.sh? Never made any sense to me and still doesn't.

**Comment by cl8n** [comment]
leaving a reminder here that "deleted" isn't the same thing as "restricted" but as of now I don't think there's any obvious way to tell them apart. would feel wrong to label penguinosity as restricted, for example

**Comment by cl8n** [comment]
instead of above I just made the extra "restricted" label not visible in some places where it feels wrong to me, like contributors page, and table columns where it would take up too much space
