### ISSUE TITLE
Add Not-Allowed/Extra Permissions notification on picks

### ISSUE THREAD

**Issue by Blooshing** [cl8n/project-loved-web#236]
With the new [Usage Permissions](https://osu.ppy.sh/wiki/en/Rules/Content_usage_permissions) wiki being public, I think it would be good to give captains/moderators notifications that a map from the not allowed category is being picked and a different notification that a Extra permission map is being picked and that one needs manual confirmation from either a coordinator or another captain. 

This is to all help to make sure maps going into loved can be preserved and not removed from either the loved category or from being downloaded entirely. 

Idea started from:
https://discord.com/channels/188630481301012481/384640068847009792/1175636638286757918

**Comment by cl8n** [comment]
as written on discord i'll address this only if it's later annoying or something, for now it's osu's problem and we don't need to care
