### ISSUE TITLE
Change so that URL's in the current round picks page open in a new tab

### ISSUE THREAD

**Issue by yasuhosu** [cl8n/project-loved-web#238]
On the current round picks page, clicking on any URL within that page, opens that URL in the same tab. 

As a little QOL enhancement, opening those links in a **new** tab would make it easier to work with I think, especially when checking creators and metadata on multiple sets in a row.

**Comment by cl8n** [comment]
does middle click not work there? forcing open in new tab is usually not a good idea cuz some people don't want that. whereas normally you can choose between same tab (left click) or new tab (middle click)

**Comment by yasuhosu** [comment]
Actually yeah, some people may not like that. You're right, middle clicks work. Closing this.
