### ISSUE TITLE
Hovering over score [?] or clicking it doesn't show anything

### ISSUE THREAD

**Issue by abraker95** [cl8n/project-loved-web#38]
Feels like it should

![image](https://user-images.githubusercontent.com/4358724/129661542-651517d8-07db-4513-8a3a-f5761f93a199.png)

**Comment by huuishuu** [comment]
It does if you hover over it for long enough, but I agree - it should appear as soon as you hover over it or at least become clickable.

![](https://i.imgur.com/pPSFnIw.png)

**Comment by cl8n** [comment]
it's the most standard usage of `title` possible, not sure why this is causing so many problems
there is no way to control how the browser displays `title` so I'll just add some tooltip-ish thing instead.
