### ISSUE TITLE
Click 'Expand' may make some text way to big

### ISSUE THREAD

**Issue by Corne2Plum3** [cl8n/project-loved-web#52]
While browsing the map listing on my phone, I clicked the 'Expand' for the map "Inspector - Disconnected Hardkore (CanBlaster Remix)", the text hidden became bigger. It affected all hidden text for all maps, where the text become bigger. (like the screenshots below) Once this bug reached, there's no way to fix the text size (clicking on close does anything...).

![Screenshot_2021-08-22-21-03-42-911_com android chrome](https://user-images.githubusercontent.com/57914482/130367176-e7cc46fe-02f7-4615-ad06-fd7935804f4a.jpg)
![Screenshot_2021-08-22-21-03-51-843_com android chrome](https://user-images.githubusercontent.com/57914482/130367180-9cb89e7a-b7ad-4826-816f-9170a2666e34.jpg)

This bug happens only with the map "Inspector K - 
Disconnected Hardkore (CanBlaster Remix)" (the 8th on the list).

**Comment by Corne2Plum3** [comment]
After checking all 'Expand' button, it happens with "witch's slave - artefatto vita" and  "PUP - See You At Your Funeral" (28th and 29th).
The common point with these 3 maps is they have a lot of text (because the guys who submitted these maps wrote a lot).
I think this bug is from this : if a comment or the whole hidden text is too long, this bug described above happens.

**Comment by cl8n** [comment]
tracking the table layout changing with long paragraph at #53 

some mobile browsers enlarge text to compensate for displaying a wide viewport on a small screen, I'm assuming that's what's happening here. what browser is this? I'll look into some way to disable that until this website has styles for mobile.

**Comment by Corne2Plum3** [comment]
I used Google Chrome in an Android device.

**Comment by cl8n** [comment]
should be fixed, reopen if it's still happening
