### ISSUE TITLE
Español should start with capital E in language selector

### ISSUE THREAD

**Issue by DannyPX** [cl8n/project-loved-web#70]
![image](https://user-images.githubusercontent.com/47347980/132095119-f78ffb54-994e-461c-bd9b-9b01ef5dd5bd.png)
Español should start with a capital C

**Comment by cl8n** [comment]
it should because these are title-cased endonyms, and I made this argument when osu! changed their capitalization, but the names here aren't my opinion and I'm just copying them from osu.
