### ISSUE TITLE
zh-cn translation

### ISSUE THREAD

**Issue by ts8zs** [cl8n/project-loved-web#93]
[zh-cn (2).zip](https://github.com/cl8n/project-loved-web/files/7256578/zh-cn.2.zip)

**Comment by ts8zs** [comment]
[zh-cn (2) - 1.zip](https://github.com/cl8n/project-loved-web/files/7256767/zh-cn.2.-.1.zip)
update

**Comment by cl8n** [comment]
added the second one, thanks for translation 🎉

**Comment by ts8zs** [comment]
rechecked the website and fixed some mistakes.
[zh.zip](https://github.com/cl8n/project-loved-web/files/7258593/zh.zip)

**Comment by cl8n** [comment]
updated
